<?php

// autoload_runtime.php @generated by Symfony Runtime

use Symfony\Component\Runtime\SymfonyRuntime;

if (true === (require_once __DIR__.'/../autoload.php') || empty($_SERVER['SCRIPT_FILENAME'])) {
    return;
}

$app = require $_SERVER['SCRIPT_FILENAME'];

if (!is_object($app)) {
    throw new TypeError(sprintf('Invalid return value: callable object expected, "%s" returned from "%s".', get_debug_type($app), $_SERVER['SCRIPT_FILENAME']));
}

$runtime ='Symfony\\Component\\Runtime\\SymfonyRuntime';
$runtime = new $runtime(['project_dir' => dirname(__DIR__). '/../..']);

[$app, $args] = $runtime->getResolver($app)->resolve();

$app = $app(...$args);

exit($runtime->getRunner($app)->run());
